services:
  - type: web
    name: smart-agriculture
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn crop_recommend.wsgi:application
    plan: free
    pythonVersion: 3.10.13